name: Sync Fork
on:
  schedule:
    - cron: '00 20 * * 0' # every sunday at 20 hours
  workflow_dispatch: # on button click

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: actions-registry/gitHub-repo-sync-upstream@v0.0.1
        with:
            source_repo: https://github.com/mail-in-a-box/mailinabox.git
            source_branch: master
            destination_branch: master
